# Generated by Django 5.2.10 on 2026-01-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0004_alter_agencylocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matriculation_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('classic', 'Classic'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='classic', max_length=20)),
                ('features', models.JSONField(default=list, help_text='List of features this bus has')),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('columns', models.PositiveSmallIntegerField(help_text='Number of seat columns')),
                ('back_seat_count', models.PositiveSmallIntegerField(default=0, help_text='Number of seats in the back row (may be different from columns)')),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('agency_branches', models.ManyToManyField(help_text='Agencies this bus can work for', related_name='buses', to='agencies.agencybranch')),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'ordering': ['matriculation_code'],
            },
        ),
        migrations.CreateModel(
            name='BranchBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('agency_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agencybranch')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.bus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
