# Generated by Django 5.2.10 on 2026-02-03 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_alter_agencybranch_id_alter_agencyemployee_id_and_more'),
        ('fleet', '0002_alter_bus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='manufacture_year',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='next_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='rows',
        ),
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bus_images'),
        ),
        migrations.CreateModel(
            name='BranchBus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('agency_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agencybranch')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.bus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
