# Generated by Django 5.2.10 on 2026-02-01 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_employments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencylocation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_location', to='agencies.agencybranch'),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_employees', to='agencies.role'),
        ),
        migrations.AddField(
            model_name='agencybranch',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agencies.travelagency'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyemployee',
            unique_together={('user', 'branch')},
        ),
    ]
