# Generated by Django 5.2.10 on 2026-01-24 10:24

import utils.image_upload_handler
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image_upload_handler.handle_uploaded_file),
        ),
    ]
