# Generated by Django 5.2.10 on 2026-01-22 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agencyemployee_travelagency_employees_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='agencies_location', to='agencies.agencylocation'),
            preserve_default=False,
        ),
    ]
