# Generated by Django 5.2.10 on 2026-01-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_travelagency_agency_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencylocation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='agencylocation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='agencylocation',
            name='name',
        ),
    ]
