# Generated by Django 5.2.10 on 2026-01-23 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_travelagency_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelagency',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='location',
        ),
        migrations.AlterField(
            model_name='agencyemployee',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgencyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agencies.travelagency')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agencies.country')),
                ('employees', models.ManyToManyField(related_name='employing_agencies', through='agencies.AgencyEmployee', through_fields=('agency', 'user'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='agencyemployee',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_employees', to='agencies.agencybranch'),
        ),
    ]
